language: python
os:
  - windows
  - linux
  - osx
python:
  - "3.5"
  - "3.6"
install:
  - pip install '.[api,test]'
script: pytest
branches:
  only:
    - master
    - conferatur
matrix:
  include:
    - { python: "3.7", dist: "xenial", os: "linux" }
  allow_failures:
    - os: windows
    - os: osx
