language: python
os:
  - windows
  - linux
  - osx
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - pip install '.[test]'
script: pytest
branches:
  only:
    - master
matrix:
  include:
    - { python: "3.7", dist: "xenial", os: "linux" }
  allow_failures:
    - os: windows
    - os: osx
    - python: "3.8-dev"
