language: python
os:
  - windows
  - linux
  - osx
python:
  - "3.5"
  - "3.6"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install '.[api,test]'
script: pytest
branches:
  only:
    - master
matrix:
  allow_failures:
    - os: windows
